### ISSUE TITLE
ScrollContextType is missing in TS definitions

### ISSUE THREAD

**Issue by joostfroon** [EmaSuriano/react-scroll-section#82] opened 2020-10-05 11:36 UTC
The error i get is: 

```../../node_modules/react-scroll-section/lib/context.d.ts(3,92): error TS2304: Cannot find name 'ScrollContextType'.```

By adding this in de lib/context.d.ts, the bug was resolved:

```
type RefsRegister = {
  [x: string]: React.RefObject<HTMLElement>;
};
type ScrollContextType = {
  registerRef: (id: string) => React.RefObject<HTMLElement> | null;
  scrollTo: (section: string) => void;
  refs: RefsRegister;
  selected: string;
};
```

Not a master in TS, so perhaps you can help me with this?

Thanx! Joost

**Comment by EmaSuriano** [comment] 2020-10-05 16:14
Hello can you share a code snippet of how you are using the library? I'm currently using this library in one of my projects and I didn't face this problem.

**Comment by joostfroon** [comment] 2020-10-06 10:09
Hey @EmaSuriano thanx for your reaction!

Code:

```
function ProductPageNav({ sections, offset }: Props) {
  const items = useScrollSections()
  return (
    <Menu offset={offset}>
      {items &&
        items.map(({ id, selected, onClick }) => (
          <MenuItem key={id} type="button" active={selected} onClick={onClick}>
            {sections[id]?.label}
          </MenuItem>
        ))}
    </Menu>
  )
}
```

```
<ScrollingProvider>
              <ProductPageNav sections={sections} offset="0" />
              <Section id={sections.information.id}>
                <ProductPageDetails product={product} />
              </Section>
            </ScrollingProvider>
```


But I think the problem is in de build, this is screenshot of the context.d.ts file, it uses types that are not imported or defined :
<img width="1078" alt="Schermafbeelding 2020-10-06 om 12 06 16" src="https://user-images.githubusercontent.com/33715654/95188207-65593500-07cc-11eb-9924-4aed0cfea165.png">

Thank you for taking the time!

**Comment by laurenskling** [comment] 2020-10-09 17:59
@EmaSuriano There are a couple of things wrong in the types which makes the whole system broken and not throwing errors. 

`types.d.ts` doesn't work, since `RefObject` is an `any` because it's not imported from `react`.

`context.ts` does `import React from 'react';` which should make it `context.tsx` for it to work. The whole typing is broken because of it. If you would do so, it would throw:
```
src/context.tsx:10:50 - error TS2304: Cannot find name 'ScrollContextType'.

10 export const ScrollContext = React.createContext<ScrollContextType>(
```

better is to change the import to `import { createContext } from 'react';`  and not make it tsx. which will still produce the error.

Now `ScrollingProvider` will also throw errors on the missing import `RefsRegister`. When you do so, a bunch of new typings errors show up. For these I know too little about the package to fix them; but I hope I inspired you to chase this down.

**Comment by EmaSuriano** [comment] 2020-10-23 15:32
Hello again guys. I am not able to reproduce the issue :/ I created a code sandbox following the code from @joostfroon, it's live here --> https://codesandbox.io/s/react-scroll-section-typescript-12mw0

I am open to fix any issue you are having with the tool, but it's a bit hard if I can't reproduce it 😅

**Comment by laurenskling** [comment] 2020-10-23 16:12
The sandbox _uses_ the package, you might not see TS errors like this. But the wrong types are _inside_ of the package.

Follow my steps stated before. Clone the repo, change `types.d.ts` to actually `import type { RefObject } from 'react'` you will see errors start popping up.

in `context.ts` change `import React from 'react';` into `import { createContext } from 'react';` you will see error start popping up.

Errors are being repressed by other faults like these.

**Comment by EmaSuriano** [comment] 2020-11-17 09:02
@laurenskling the problem is that if you declare an `import` or `export` inside `types.d.ts` then this file is not considered a  declaration type file anymore, and therefore I would have to export all the types inside this file and import then whenever I want to use them.

The good thing of leaving this file only with declaration of types is that Typescript can resolve these definitions when in running `tsc`. You can check that the project is typed correctly by running `yarn tsc`.

**Comment by laurenskling** [comment] 2020-11-17 12:31
Because of https://github.com/EmaSuriano/react-scroll-section/blob/master/tsconfig.json#L15 you don't get errors, so that `tsc` checks is a false positive.

Make the proposed changes to `context.ts` you will see Error start popping up. `tsc` isn't throwing errors, because it's unable to, because things are wrong. (using react in a `.ts` file). It's a false positive you get no errors.

**Comment by EmaSuriano** [comment] 2022-10-17 19:16
With the latest update of the library, this issue should be fixed. I will proceed to close this issue, feel free to re-open it in case you are still facing it.

**Closed by EmaSuriano** 2022-10-17 19:16 UTC
